"""
Docs Analyzer prompts package.
"""

from .response_summary import (
    RESPONSE_SUMMARY_SYSTEM_PROMPT,
    RESPONSE_SUMMARY_REFERENCE_PROMPT
)

from .query_relevance import (
    QUERY_RELEVANCE_CONTEXT_PROMPT,
    QUERY_RELEVANCE_INSTRUCTIONS_PROMPT
)

from .query_rewriting import (
    QUERY_REWRITING_PROMPT
)

from .response_generation import (
    RESPONSE_GENERATION_CONTEXT_PROMPT,
    RESPONSE_GENERATION_REFERENCE_PROMPT,
    RESPONSE_GENERATION_FINAL_INSTRUCTIONS
)

from .context_messages import (
    CONTEXT_SYSTEM_MESSAGE,
    CONTEXT_HUMAN_MESSAGE
)

__all__ = [
    'RESPONSE_SUMMARY_SYSTEM_PROMPT',
    'RESPONSE_SUMMARY_REFERENCE_PROMPT',
    'QUERY_RELEVANCE_CONTEXT_PROMPT',
    'QUERY_RELEVANCE_INSTRUCTIONS_PROMPT',
    'QUERY_REWRITING_PROMPT',
    'RESPONSE_GENERATION_CONTEXT_PROMPT',
    'RESPONSE_GENERATION_REFERENCE_PROMPT',
    'RESPONSE_GENERATION_FINAL_INSTRUCTIONS',
    'CONTEXT_SYSTEM_MESSAGE',
    'CONTEXT_HUMAN_MESSAGE'
]
