from fastmcp import FastMCP
from tools.docs_analyser.main import DocsAnalyzer
from tools.docs_analyser.config import Config as docs_config
from tools.docs_analyser.models import FileInfo
from tools.data_interpreter.main import DataInterpreter
from tools.data_interpreter.config import Config as data_config
from tools.content_writer.main import ContentWriter
from tools.content_writer.config import Config as content_config
import os
import json
import concurrent.futures
from typing import List

mcp = FastMCP(stateless_http=True)

@mcp.tool
def docs_analysis(query: list[str] | str, filenames: list[str], save_outputs: bool = False) -> dict:
    """
    Docs-Analyser Tool [UNSTRUCTURED DATA]

    A specialised LLM-powered tool that searches and analyses unstructured data 
    sources (PDFs, TXTs, DOCs, PPTs, webpages, etc.) to extract information relevant 
    to a list of queries/questions. For each query it will search across all the list of files provided and 
    return relevant information (a response) with respect to each relevant file for each of the queries
    along with the references used from that file to generate the response

    Parameters
    ----------
    query : list[str] or str
        A list of questions or information requests to be answered, or a single question as a string.
    filenames : list[str]
        A list of file names or file paths representing the unstructured data sources to be analyzed.
        Note: Do not use temp files as input. If temp files are provided, the tool will not be able to extract references from them.
    save_outputs : bool, optional
        If True, the output will be saved in a folder named 'temp' (default is False).
        This is important for workflows that require intermediate results to be persisted and reused by other tools or steps.
        Always set to True whenever the data generated by the docs analyzer will be used in further steps.

    Important
    ---------
    - This tool is not intended for pure summarization tasks, it is internally handled within the tool and it provides a summary for all the queries across the different sets of files. It should only be used to answer specific queries or information requests.
    - Tasks like data analytics, data transformation, data cleaning, tagging/coding etc. are not intended to be done using this tool.
    - This tool should only be used for answering specific queries or information requests.
    - Avoid multiple calls to the docs analyser for the same set of files, as it is a resource intesive tool, so try to fit most queries in one task for a specific set of files, and do not make calls for summarization tasks

    Returns
    -------
    dict
        A structured response containing:
        - Relevant answers to each query for every file that was found to be relevant.
        - References to the specific files and content used to generate each response.
        - A summary of the responses for all queries and all relevant files.
        - If save_outputs is True, the path to the generated temp file is included under the 'temp_file' key.
    """
    filenames_objs = [FileInfo(filename=filename, displayname=filename, filetype="txt", id=filename) for filename in filenames]

    def run_single(single_query: str) -> dict:
        docs_analyzer = DocsAnalyzer(
            filenames=filenames_objs,
            query=single_query
        )
        analysis_result = docs_analyzer.analyze_files()
        if hasattr(analysis_result, "to_dict"):
            results_dict_local = analysis_result.to_dict()
        else:
            try:
                from dataclasses import asdict
                results_dict_local = asdict(analysis_result)
            except Exception:
                results_dict_local = dict(getattr(analysis_result, "__dict__", {}))
        return results_dict_local

    # If a list of queries is provided, run them in parallel and return a mapping
    if isinstance(query, list):
        results: dict[str, dict] = {}
        temp_files: dict[str, str] = {}

        with concurrent.futures.ThreadPoolExecutor(max_workers=min(8, max(1, len(query)))) as executor:
            future_map = {executor.submit(run_single, q): q for q in query}
            for future in concurrent.futures.as_completed(future_map):
                q = future_map[future]
                try:
                    results_dict = future.result()
                except Exception as e:
                    results_dict = {
                        "file_level_responses": [{
                            "response": f"Error processing query: {q}. {str(e)}",
                            "references": [],
                            "pointers": [],
                            "questions": [],
                            "confidence": "LOW",
                            "filedetails": []
                        }],
                        "token_tracker": {}
                    }
                results[q] = results_dict

        if save_outputs:
            os.makedirs("temp", exist_ok=True)
            import hashlib
            try:
                import os as _os
                safe_base = _os.path.basename(filenames[0]) if filenames else "output"
            except Exception:
                safe_base = filenames[0] if filenames else "output"

            # Create a single combined results file for all queries
            combined_key = "|".join([str(q) for q in query])
            combined_hash = hashlib.md5(combined_key.encode("utf-8")).hexdigest()[:8]
            combined_path = f"temp/{safe_base}_results_{combined_hash}.json"

            try:
                with open(combined_path, "w", encoding="utf-8") as f:
                    json.dump({"results": results}, f, ensure_ascii=False, indent=2)
            except Exception:
                combined_path = ""

            # Build a flattened view across all queries for downstream tools
            flattened_rows = []
            try:
                for q, res in results.items():
                    file_level_responses = res.get("file_level_responses", []) or []
                    # Try to determine a display base from first filedetails if present
                    for entry in file_level_responses:
                        display_name = None
                        try:
                            filedetails = entry.get("filedetails", []) or []
                            if filedetails and isinstance(filedetails, list):
                                display_name = filedetails[0].get("displayname")
                        except Exception:
                            display_name = None
                        filename_for_row = display_name or safe_base

                        response_text = entry.get("response", "")

                        flattened_rows.append({
                            "query": q,
                            "filename": filename_for_row,
                            "response": response_text
                        })
            except Exception:
                flattened_rows = []

            flat_csv_path = f"temp/{safe_base}_flat_{combined_hash}.csv"
            flat_json_path = f"temp/{safe_base}_flat_{combined_hash}.json"

            if flattened_rows:
                import csv as _csv
                header = ["query", "filename", "response"]
                with open(flat_csv_path, "w", encoding="utf-8", newline="") as csvfile:
                    writer = _csv.DictWriter(csvfile, fieldnames=header)
                    writer.writeheader()
                    for row in flattened_rows:
                        writer.writerow(row)
                with open(flat_json_path, "w", encoding="utf-8") as jf:
                    json.dump(flattened_rows, jf, ensure_ascii=False, indent=2)

            payload = {"results": results}
            # Provide a single temp file for downstream steps; also include combined raw results path
            payload["temp_file"] = flat_json_path if flattened_rows else combined_path
            return payload

        return {"results": results}

    # Otherwise, treat as a single-query flow (backwards compatible response shape)
    single_query = query
    results_dict = run_single(single_query)

    if save_outputs:
        os.makedirs("temp", exist_ok=True)
        import hashlib
        base_name = filenames[0] if filenames else "output"
        query_hash = hashlib.md5(single_query.encode("utf-8")).hexdigest()[:8]
        try:
            import os as _os
            safe_base = _os.path.basename(base_name)
        except Exception:
            safe_base = base_name
        output_filename = f"temp/{safe_base}_result_{query_hash}.json"
        results_to_save = {**results_dict, "query": single_query}
        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(results_to_save, f, ensure_ascii=False, indent=2)

        flattened_rows = []
        try:
            file_level_responses = results_dict.get("file_level_responses", []) or []
            for entry in file_level_responses:
                display_name = None
                try:
                    filedetails = entry.get("filedetails", []) or []
                    if filedetails and isinstance(filedetails, list):
                        display_name = filedetails[0].get("displayname")
                except Exception:
                    display_name = None
                filename_for_row = display_name or safe_base

                response_text = entry.get("response", "")

                flattened_rows.append({
                    "query": single_query,
                    "filename": filename_for_row,
                    "response": response_text
                })
        except Exception:
            flattened_rows = []

        from pathlib import Path
        import csv as _csv

        flat_csv_path = f"temp/{safe_base}_flat_{query_hash}.csv"
        flat_json_path = f"temp/{safe_base}_flat_{query_hash}.json"

        if flattened_rows:
            header = ["query", "filename", "response"]
            with open(flat_csv_path, "w", encoding="utf-8", newline="") as csvfile:
                writer = _csv.DictWriter(csvfile, fieldnames=header)
                writer.writeheader()
                for row in flattened_rows:
                    writer.writerow(row)
            with open(flat_json_path, "w", encoding="utf-8") as jf:
                json.dump(flattened_rows, jf, ensure_ascii=False, indent=2)

        results_dict = {**results_dict, "temp_file": flat_json_path}

    return results_dict


@mcp.tool
def data_interpreter(query: str, filenames: list[dict], save_outputs: bool = False) -> dict:
    """
    Data-Interpreter Tool [STRUCTURED DATA]

    A specialised LLM-Powered tool designed to search and analyse a structured dataset (tables). 
    These datasets could be tables in relational databases or temporary sources created by some other process in a multi-step workflow
    It can be used only in the following scenarios:
    - While trying to calculate some aggregate statistics over a bunch of numeric columns
    - While trying to calculate some aggregate statistics over text heavy columns by first doing annotation (targeted open-ended coding) to create quantifiable and discrete fields (ordinal/nominal categories)

    It cannot be used in the following scenarios because writing of SQL queries to calculate statistics will not be possible:
    - While trying to identify broad themes and concepts over text heavy columns. In such cases, calculation of aggregate statistics will not be possible 
    - While trying to identify broad insights over text heavy columns. In these cases also, a tool like data intepreter is not required

    Capabilities
    ------------
    - Plan and execute multi-step data transformation and aggregation workflows
    - Write SQL queries on top of datasets/tables to filter, aggregate, and summarise quantifiable columns (numeric fields or ordinal/nominal categories)
    - Do the above over a single or multiple tables, either in isolation or by joining them at appropriate steps
    - Transform text heavy columns by performing annotation (targeted open-ended coding) to create quantifiable data on top of which SQL queries can be written

    Parameters
    ----------
    query : str
        A clear instruction specifying which fields to analyze and what metrics to calculate. 
        Metrics must be based on numeric or categorical fields, using SQL queries for filtering and aggregation.
        If fields are mostly text, explain how to annotate them to create quantifiable data before calculating metrics.
        Do not attempt to calculate metrics directly from text fields without proper annotation.

        Queries made should be perfectly describing what information you want, what you want to be annotated, a very targeted query.
        
        Example:
        1. What is the percentage count of people using Airtel, Jio and VI?
        2. How many people use plans above INR 600?
        ....

    filenames : list[dict]
        A list of relational database tables with metadata. 
        In the case of temp files, each dict should be of the form:
            {
                'displayname': '<user-friendly name for the file>',
                'filename': '<path to the file or table>', # Replace this path with the original path of the temp file in case previous step output is to be used
                'filetype': '<type of file, e.g., "temp", "csv", "db", etc.>'
            }
        For other sources, include appropriate metadata such as table name, unique ID, and source URI.
    save_outputs : bool, optional
        If True, the output will be saved to a folder named 'temp' (default is False).

    IMPORTANT: The data interpreter tool is highly resource intensive. Avoid making multiple or repeated calls—this tool is designed to process large, comprehensive queries in a single invocation. Always consolidate your requirements and invoke the data interpreter only once per workflow whenever possible.

    Returns
    -------
    dict
        A structured response containing one or more output datasets and 
        relevant inferences that can be used to answer the query.
    """
    client = "64sqs"
    project_id = "116"
    model_type = "gpt-4.1"
    api_key = data_config.OPENAI_API_KEY

    interpreter = DataInterpreter(
        client=client,
        project_id=project_id,
        filenames=filenames,
        model_type=model_type,
        api_key=api_key,
        query=query
    )
    final_response, token_tracker = interpreter.run()
    results_dict = final_response

    if save_outputs:
        os.makedirs("temp", exist_ok=True)
        import hashlib
        base_name = filenames[0].get("filename", "output") if filenames else "output"
        query_hash = hashlib.md5(query.encode("utf-8")).hexdigest()[:8]
        try:
            import os as _os
            safe_base = _os.path.basename(base_name)
        except Exception:
            safe_base = base_name
        output_filename = f"temp/{safe_base}_data_result_{query_hash}.json"
        results_to_save = {**results_dict, "query": query}
        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(results_to_save, f, ensure_ascii=False, indent=2)
        results_dict = {**results_dict, "temp_file": output_filename}

    return results_dict

@mcp.tool
def content_writer(
    filenames: List[str], 
    target_document_type: str, 
    target_document_length: str, 
    target_document_brief: str,
    save_outputs: bool = False
) -> dict:
    """
    Content-Writer Tool [CONTENT GENERATION]

    A specialized LLM-powered tool that generates structured documents from notes and specifications.
    It can create Word documents (.docx) or HTML pages from a collection of text snippets and 
    high-level document requirements. The tool orchestrates a two-step process: first generating 
    a logical outline, then creating detailed content for each section.

    Capabilities
    ------------
    - Generate structured outlines based on notes and target specifications
    - Create detailed content for each section following the outline
    - Export to Word documents (.docx) or HTML pages
    - Maintain consistent formatting and structure
    - Track token usage for cost monitoring
    - Support for custom document lengths and briefs

    Parameters
    ----------
    filenames : List[str]
        A list of file paths whose contents will be used as source material for
        content generation. The tool will read each file as UTF-8 text (errors ignored)
        and feed the combined texts as notes to the writer.
    target_document_type : str
        The output format for the generated document. Supported types:
        - "doc": Generates a Word document (.docx file)
        - "html": Generates an HTML page (.html file)
    target_document_length : str
        Specifies the desired length of the document. Examples:
        - "500 words" for text-based documents
        - "10 slides" for presentation-style content
        - "2000 words" for longer documents
    target_document_brief : str
        A comprehensive and detailed description that clearly articulates the subject matter the content should address, outlines its intended goals and purpose, defines the specific audience it is meant for, and includes any relevant instructions regarding tone, style, formatting, structure, or other unique requirements. The more specific and elaborate the brief, the better it will guide the AI to produce content that is precise, tailored, and fully aligned with your needs.
    save_outputs : bool, optional
        If True, the generated document will be saved to the 'temp' directory (default: False).
        The file path will be included in the response under the 'output_file' key.


    How to Use
    ----------
    - The files and brief given to the document serve as the backbone to how the tool will perform.
    - Files can be outputs from previous tool calls (e.g., temp JSON/CSV) or user-provided source material.
    - Ensure the selected files contain the exact information you want the document to reflect.
    - The brief should guide how the document is organized and styled.

    Files should preferably capture inferences or raw content from the last tool call
    when used in multi-step workflows, so the generated document reflects the latest
    results.

    Example for target document brief:
    
    Using the question-and-answer interview data from doctors in India, the United States, and Germany, produce a thorough comparative analysis organized by the following country pairs:

    - India vs Germany
    - India vs United States
    - United States vs Germany

    For each pairwise comparison, analyze and compare these aspects:
    - Healthcare System Preparedness (including ICU capacity, resource allocation, hospital reorganization strategies, and use of data-driven decision-making)
    - Impact on Healthcare Workers (such as staffing shortages, burnout, coping mechanisms, and availability of mental health support)
    - Vaccination and Public Trust (rollout efficiency, public communication and trust-building strategies, and management of vaccine hesitancy)
    - Technology Adoption (implementation of telemedicine, use of digital dashboards, AI/analytics, and inter-facility coordination)
    - Unique Lessons & Insights (notable country-specific practices or challenges that stood out)

    Present the analysis in a clear, structured format:
    - Create a main section for each country pair, with a heading.
    - For each aspect within the pair, use concise bullet points to summarize similarities, differences, and patterns found in the source interviews.
    - Where relevant, emphasize actionable insights or recommendations that emerge from each comparison, with a focus on implications for improving future pandemic planning and healthcare crisis response.

    Returns
    -------
    dict
        A structured response containing:
        - 'draft_content': List of sections with titles and content
        - 'draft_name': Generated name for the document
        - 'token_tracker': Dictionary tracking token usage by operation
        - 'output_file': Path to saved file (if save_outputs=True)
        - 'document_type': The type of document that was generated
        - 'status': Success/failure status of the operation
    """
    try:
        # Read files into notes, handling JSON files specially
        def _read_file_to_notes(path: str) -> List[str]:
            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()
                
                # Try to parse as JSON first
                try:
                    import json
                    data = json.loads(content)
                    
                    # Handle different JSON structures
                    if isinstance(data, list):
                        # Handle list of objects (like the flat JSON format)
                        notes = []
                        for item in data:
                            if isinstance(item, dict):
                                # Extract meaningful content from each object
                                note_parts = []
                                if "query" in item:
                                    note_parts.append(f"Query: {item['query']}")
                                if "response" in item:
                                    note_parts.append(f"Response: {item['response']}")
                                if "filename" in item:
                                    note_parts.append(f"Source: {item['filename']}")
                                
                                if note_parts:
                                    notes.append(" | ".join(note_parts))
                        return notes
                    
                    elif isinstance(data, dict):
                        # Handle single object or nested structure
                        notes = []
                        
                        # Check for common patterns in docs analyzer results
                        if "results" in data:
                            results = data["results"]
                            if isinstance(results, dict):
                                for query, result in results.items():
                                    if isinstance(result, dict) and "file_level_responses" in result:
                                        for response in result["file_level_responses"]:
                                            if isinstance(response, dict):
                                                note_parts = []
                                                if "response" in response:
                                                    note_parts.append(f"Response: {response['response']}")
                                                if "filedetails" in response and response["filedetails"]:
                                                    filedetails = response["filedetails"][0] if isinstance(response["filedetails"], list) else response["filedetails"]
                                                    if isinstance(filedetails, dict) and "displayname" in filedetails:
                                                        note_parts.append(f"Source: {filedetails['displayname']}")
                                                if note_parts:
                                                    notes.append(" | ".join(note_parts))
                        
                        # Check for data interpreter results
                        elif "output_datasets" in data:
                            for dataset in data["output_datasets"]:
                                if isinstance(dataset, dict) and "inferences" in dataset:
                                    notes.append(f"Analysis: {dataset['inferences']}")
                        
                        # Generic handling for other dict structures
                        else:
                            for key, value in data.items():
                                if isinstance(value, str) and len(value.strip()) > 10:
                                    notes.append(f"{key}: {value}")
                        
                        return notes if notes else [content]
                    
                    else:
                        return [str(data)]
                
                except json.JSONDecodeError:
                    # Not JSON, treat as plain text
                    return [content] if content.strip() else []
                
            except Exception:
                return []

        notes = []
        for _fp in (filenames or []):
            if isinstance(_fp, str):
                file_notes = _read_file_to_notes(_fp)
                notes.extend(file_notes)

        # Initialize the ContentWriter
        writer = ContentWriter()

        # Generate the document
        draft_content, draft_name, token_tracker = writer.create_draft(
            target_document_type=target_document_type,
            target_document_length=target_document_length,
            target_document_brief=target_document_brief,
            notes=notes,
        )
        
        # Prepare the response
        result = {
            "draft_content": draft_content,
            "draft_name": draft_name,
            "token_tracker": token_tracker,
            "document_type": target_document_type,
            "status": "success"
        }
        
        # Save outputs if requested
        if save_outputs:
            os.makedirs("temp", exist_ok=True)
            
            # Create a safe filename
            safe_filename = "".join(c for c in draft_name if c.isalnum() or c in (' ', '_')).rstrip()
            
            if target_document_type == "doc":
                output_file = f"temp/{safe_filename}.docx"
            elif target_document_type == "html":
                output_file = f"temp/{safe_filename}.html"
            else:
                output_file = f"temp/{safe_filename}.txt"
            
            result["output_file"] = output_file
            
            # Save the results as JSON for reference
            results_json = {
                "draft_content": draft_content,
                "draft_name": draft_name,
                "token_tracker": token_tracker,
                "document_type": target_document_type,
                "target_brief": target_document_brief,
                "target_length": target_document_length
            }
            
            json_file = f"temp/{safe_filename}_content_data.json"
            with open(json_file, "w", encoding="utf-8") as f:
                json.dump(results_json, f, ensure_ascii=False, indent=2)
            
            result["json_file"] = json_file
        
        return result
        
    except Exception as e:
        return {
            "status": "error",
            "error_message": str(e),
            "document_type": target_document_type,
            "draft_content": [],
            "token_tracker": {}
        }

if __name__ == "__main__":
    mcp.run(transport="streamable-http")